title: Homepage
description: My website and blog
author: Leigh Jia
github: https://github.com/ljia9
about: College student and software developer interested in Math and Computer Science
disqus_shortname: blogposts
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/leigh-jia-219513109"

urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/ljia9
    - text: XML Feed
      url: /feed.xml

url: "https://ljia9.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
